cities:
  - name: Bogota
    latitude: 4.6097
    longitude: -74.0818

  - name: Barranquilla
    latitude: 10.9685
    longitude: -74.7813

  - name: Medellin
    latitude: 6.2518
    longitude: -75.5636

  - name: Cali
    latitude: 3.4372
    longitude: -76.5225

weather:
  data_type: hourly
  variables:
    - temperature_2m
    - relative_humidity_2m
    - precipitation_probability
    - cloud_cover
    - wind_speed_10m
  timezone: America/Bogota
  forecast_days: 1

execution:
  run_times:
    - "08:00"
    - "13:00"
    - "18:00"

url:
  weather:
    - "https://api.open-meteo.com/v1/forecast"